### ISSUE TITLE
No snakes included?

### ISSUE THREAD

**Issue by ariskyr** [thesmallcreeper/inMyRoom_vulkan#1]
Dear friend,
My name is Kumalo, I live in Ethiopia and I am 59 yearls old.

I recently bought a version of the vulkan but for some reason I received no snakes in my room?????/?
What is the meaning of this, I thought you were a respectable person! You will answer for this!

If it was issue of shipment, it is fine I expect 3 lifeline packages with my snakes at my address.
Tank you very much good sir.

**Comment by thesmallcreeper** [comment]
You got scummed! ezzy moneyyy. closing the issue
